repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git --no-update --since-commit HEAD --trust-local-git-config --fail file://.'
        language: system
        stages: ["pre-commit", "pre-push"]
        pass_filenames: false
      - id: shellcheck
        name: ShellCheck
        description: Lint shell scripts for errors before execution.
        entry: shellcheck
        language: system
        types: [shell]
        files: ^scripts/.*\.sh$
